### PR TITLE
nicknames, metric parameters, empty inputs, and memory leaks

### PR DESCRIPTION
**Pull request by seanmacavaney**

### CODE REVIEW

**Comment by seanmacavaney** [comment]
Also now support for #12

**Comment by seanmacavaney** [comment]
hmmm, gotta look into the failing build.

**Comment by seanmacavaney** [comment]
Alright, includes fixes for #12 #13 #15 and #17

**Comment by seanmacavaney** [comment]
done

**Comment by cvangysel** [comment]
Thanks @seanmacavaney! I want to take another closer look at this later, before pushing out a new release to PyPi. However, I'll merge this now so that it's installable by pointing pip to the repository.

**Pull request merged**
